language: java
install: true
dist: trusty
jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew
script:
  - ./gradlew build --stacktrace
  - pwd
  - cd build/libs
  - ls

deploy:
  provider: releases
  #api_key:
   #  secure: travis encrypt -r amitshankarsinha/Github-Travis-DemoProject
  api_key: dbf14021c6350c93f1e3c33c9303155906a86e2e
  #user: "amitshankarsinha"
  #password: "semester#123"
  file: "build/libs/githubTravisIntregration.jar"
  skip_cleanup: true
  on:
    tags: false
    branch: master
