language: java
install: true
dist: trusty
jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew
script:
  - ./gradlew build --stacktrace
  - ./gradlew jar --stacktrace

deploy:
  provider: releases
  user: "amitshankarsinha"
  password: "semister#123"
  file: "build/libs/githubTravisIntregration.jar"
  skip_cleanup: true
  on:
    tags: false
    branch: master
