language: java
install: true
dist: trusty
jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew
script:
  - ./gradlew build --stacktrace
  - pwd
  - cd build/libs
  - ls
  #- ./gradlew jar --stacktrace

deploy:
  provider: releases
 # api_key:
   #  secure: travis encrypt -r amitshankarsinha/Github-Travis-DemoProject
  user: "amitshankarsinha"
  password: "semister#1"
  file: "build/libs/githubTravisIntregration.jar"
  skip_cleanup: true
  on:
    tags: false
    branch: master
