language: java
install: true
dist: trusty
jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew
script:
  - ./gradlew build --stacktrace
  - pwd
  - cd build/libs
  - ls

deploy:
  provider: releases
  api_key: $OT
  file: "/home/travis/build/amitshankarsinha/Github-Travis-DemoProject/build/libs/githubTravisIntregration.jar"
  skip_cleanup: true
  name: Github-Travis-Integration v$(date +'%d.%m.%Y')
  on:
    tags: true
    branch: master
 
